### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by chaoliu** [throneless-tech/hubot-signal-service#7]
Loading external-scripts from npm packages hubot-signal-service
[Sun Feb 02 2020 19:31:08 GMT+0800 (China Standard Time)] ERROR Error loading scripts from npm package - TypeError: require(...) is not a function
  at /Users/io/Desktop/work/bot/zoom/node_modules/hubot/src/robot.js:411:15
  at Array.forEach (<anonymous>:null:null)
  at Robot.loadExternalScripts (/Users/io/Desktop/work/bot/zoom/node_modules/hubot/src/robot.js:409:25)
  at /Users/io/Desktop/work/bot/zoom/node_modules/hubot/bin/hubot.js:207:13
  at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

**Comment by chaoliu** [comment]
> Loading external-scripts from npm packages hubot-signal-service
> [Sun Feb 02 2020 19:31:08 GMT+0800 (China Standard Time)] ERROR Error loading scripts from npm package - TypeError: require(...) is not a function
> at /Users/io/Desktop/work/bot/zoom/node_modules/hubot/src/robot.js:411:15
> at Array.forEach (:null:null)
> at Robot.loadExternalScripts (/Users/io/Desktop/work/bot/zoom/node_modules/hubot/src/robot.js:409:25)
> at /Users/io/Desktop/work/bot/zoom/node_modules/hubot/bin/hubot.js:207:13
> at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

v12.4.0   @ macOS  10.15.2
